project_id = "ubnadwskxlrskoaqsprr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-content]
verify_jwt = false

[functions.generate-creative]
verify_jwt = false
